server:
  port: 10111
  tomcat:
    accept-count: 1024
    max-connections: 10240
    max-threads: 2048
rest:
  auth-open: true
  sign-open: false
  env-product: false # 是否正式环境 true 正式 false 测试
  env-pay: true # 支付环境 true 正式 false 测试
  env-sendMSG: false # 是否真实发送短信 true 发送 false 不发送
guns:
  file-upload-path: /mnt/data/java/xishi/prod/upload/

push:
  model: false

netty:
  port: 10102
  host: 127.0.0.1

socketio:
  host: localhost
  port: 10107
  #设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  #设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000


## elasticSearch集群 ##
elasticsearch:
  cluster-name: relianba
  cluster-nodes: 172.16.56.132:9300,172.16.96.88:9300,172.16.96.89:9300
  sniff: true

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  datasource:
    url: jdbc:mysql://localhost:3306/xishi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: remote
    password: nahanMysqlPwd&&RemoteRemote2019nahan
    db-name: xishi
    filters: log4j,wall,mergeStat
  redis:
    host: 127.0.0.1
    password: nahanRedisPwsIsVerySimple&&
    port: 9520
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  freemarker:
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    content-type: text/html

### 分布式锁 ##
#redisson:
#  address: redis://127.0.0.1:9520
#  password: nahanRedisPwsIsVerySimple&&

logging:
  level.root: warn
  level.com.stylefeng: info
  path: /mnt/data/java/xishi/prod/logs/
  file: rest.log