###################  guns配置  ###################
guns:
  swagger-open: false #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  file-upload-path: /mnt/data/java/xishi/prod/upload/  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 10101

netty:
  port: 10102
  host: 127.0.0.1

web3j:
  admin-client: true
  client-address: https://rinkeby.infura.io/v3/874211e851e44645bf8312a2c7bc5316
  from-address: 0x217FfFad308202890e95E342ddCaC4FdF7bD6997
  from-privatekey: 92502082592439454d8d8d7edf3f0dd539a2c7c00d885c6115e458077b59443d

###################  spring配置  ###################
spring:
  datasource:
    url: jdbc:mysql://172.17.57.12:3306/xishi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: remote
    password: 202005050213KkXx@$%..MYSQL..//
    db-name: xishi
    filters: log4j,wall,mergeStat
  redis:
    host: 172.17.57.12
    port: 6379
    password: xishi!@#redispwd
    database: 4
logging:
  level.root: info
  level.com.stylefeng: debug
  path: /home/project/java/xishi/logs/
  file: admin.log