-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 13:10:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema daikuan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `daikuan` ;

-- -----------------------------------------------------
-- Schema daikuan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daikuan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `daikuan` ;

-- -----------------------------------------------------
-- Table `eb_dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_dept` ;

CREATE TABLE IF NOT EXISTS `eb_dept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NULL DEFAULT NULL COMMENT '排序',
  `pid` INT NULL DEFAULT NULL COMMENT '父部门id',
  `pids` VARCHAR(255) NULL DEFAULT NULL COMMENT '父级ids',
  `simplename` VARCHAR(45) NULL DEFAULT NULL COMMENT '简称',
  `fullname` VARCHAR(255) NULL DEFAULT NULL COMMENT '全称',
  `tips` VARCHAR(255) NULL DEFAULT NULL COMMENT '提示',
  `version` INT NULL DEFAULT NULL COMMENT '版本（乐观锁保留字段）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '部门表';


-- -----------------------------------------------------
-- Table `eb_dict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_dict` ;

CREATE TABLE IF NOT EXISTS `eb_dict` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '		',
  `num` INT NULL DEFAULT NULL COMMENT '排序',
  `pid` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `tips` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '字典表';


-- -----------------------------------------------------
-- Table `eb_login_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_login_log` ;

CREATE TABLE IF NOT EXISTS `eb_login_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logname` VARCHAR(255) NULL DEFAULT NULL COMMENT '日志名称',
  `adminid` INT NULL DEFAULT NULL COMMENT '管理员id',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `succeed` VARCHAR(255) NULL DEFAULT NULL COMMENT '是否执行成功',
  `message` TEXT NULL COMMENT '具体消息',
  `ip` VARCHAR(127) NULL DEFAULT NULL COMMENT '登录ip',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '登录记录';


-- -----------------------------------------------------
-- Table `eb_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_menu` ;

CREATE TABLE IF NOT EXISTS `eb_menu` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL COMMENT '菜单编号',
  `pcode` VARCHAR(255) NULL DEFAULT NULL COMMENT '菜单父编号',
  `pcodes` VARCHAR(255) NULL DEFAULT NULL COMMENT '当前菜单的所有父菜单编号',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '菜单名称',
  `icon` VARCHAR(255) NULL DEFAULT NULL COMMENT '菜单图标',
  `url` VARCHAR(255) NULL DEFAULT NULL COMMENT 'url地址\n\n\n',
  `num` INT NULL DEFAULT NULL COMMENT '菜单排序号',
  `levels` INT NULL DEFAULT NULL COMMENT '菜单层级',
  `ismenu` INT NULL DEFAULT NULL COMMENT '是否是菜单（1：是  0：不是）',
  `tips` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
  `status` INT NULL DEFAULT NULL COMMENT '菜单状态 :  1:启用   0:不启用',
  `isopen` INT NULL DEFAULT NULL COMMENT '是否打开:    1:打开   0:不打开',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `eb_notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_notice` ;

CREATE TABLE IF NOT EXISTS `eb_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `creater` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '通知表';


-- -----------------------------------------------------
-- Table `eb_operation_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_operation_log` ;

CREATE TABLE IF NOT EXISTS `eb_operation_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logtype` VARCHAR(255) NULL DEFAULT NULL,
  `logname` VARCHAR(255) NULL DEFAULT NULL,
  `adminid` INT NULL DEFAULT NULL,
  `classname` VARCHAR(255) NULL DEFAULT NULL,
  `method` TEXT NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `succeed` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '操作日志';


-- -----------------------------------------------------
-- Table `eb_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_relation` ;

CREATE TABLE IF NOT EXISTS `eb_relation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menuid` BIGINT NULL DEFAULT NULL COMMENT '菜单id',
  `roleid` INT NULL DEFAULT NULL COMMENT '角色id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色和菜单关联表';


-- -----------------------------------------------------
-- Table `eb_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_role` ;

CREATE TABLE IF NOT EXISTS `eb_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NULL DEFAULT NULL,
  `pid` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `deptid` INT NULL DEFAULT NULL,
  `tips` VARCHAR(255) NULL DEFAULT NULL,
  `version` INT NULL DEFAULT NULL,
  `describetion` VARCHAR(255) NULL DEFAULT '' COMMENT '角色描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `eb_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_admin` ;

CREATE TABLE IF NOT EXISTS `eb_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `account` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATETIME NULL DEFAULT NULL,
  `sex` INT NULL DEFAULT NULL COMMENT '性别（1：男 2：女）',
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `roleid` VARCHAR(255) NULL DEFAULT NULL,
  `deptid` INT NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `version` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `eb_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_staff` ;

CREATE TABLE IF NOT EXISTS `eb_staff` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `staff_no` VARCHAR(45) NOT NULL COMMENT '工号',
  `name` VARCHAR(45) NOT NULL COMMENT '姓名',
  `leader_id` BIGINT(20) NULL DEFAULT 0 COMMENT '负责人',
  `url` VARCHAR(255) NULL DEFAULT '' COMMENT '短链接地址',
  `state` SMALLINT(6) NULL DEFAULT 0 COMMENT '状态 0 正常 1 禁用',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `leaderId` (`leader_id` ASC))
ENGINE = InnoDB
COMMENT = '员工';


-- -----------------------------------------------------
-- Table `eb_leader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_leader` ;

CREATE TABLE IF NOT EXISTS `eb_leader` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(125) NULL DEFAULT '' COMMENT '店铺名称',
  `name` VARCHAR(64) NOT NULL COMMENT '负责人姓名',
  `state` SMALLINT(6) NULL DEFAULT 0 COMMENT '状态 0 正常 1 禁用',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '负责人';


-- -----------------------------------------------------
-- Table `eb_apply_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_apply_info` ;

CREATE TABLE IF NOT EXISTS `eb_apply_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT '' COMMENT '用户姓名',
  `id_card` VARCHAR(45) NULL DEFAULT '' COMMENT '身份证号',
  `bank_card` VARCHAR(45) NULL DEFAULT '' COMMENT '银行卡号',
  `phone` VARCHAR(45) NULL DEFAULT '' COMMENT '手机号',
  `recommend` VARCHAR(45) NULL DEFAULT '' COMMENT '推荐工号',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idCard` (`id_card` ASC),
  INDEX `phone` (`phone` ASC))
ENGINE = InnoDB
COMMENT = '申请信息';


-- -----------------------------------------------------
-- Table `eb_banner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_banner` ;

CREATE TABLE IF NOT EXISTS `eb_banner` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL COMMENT '地址',
  `name` VARCHAR(45) NULL DEFAULT '' COMMENT '名称',
  `location` SMALLINT(6) NULL DEFAULT 0 COMMENT '位置 0 首页',
  `or_sort` INT NULL DEFAULT 0 COMMENT '排序 大靠前',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'banner图';


-- -----------------------------------------------------
-- Table `eb_common_params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_common_params` ;

CREATE TABLE IF NOT EXISTS `eb_common_params` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL COMMENT 'key',
  `type` VARCHAR(45) NOT NULL COMMENT '类型',
  `value` LONGTEXT NULL DEFAULT NULL COMMENT '值 通过 key type 获取唯一数据',
  `description` VARCHAR(64) NULL DEFAULT '' COMMENT '值 描述',
  `extra` VARCHAR(45) NULL DEFAULT '' COMMENT '拓展参数',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eb_sesame_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_sesame_score` ;

CREATE TABLE IF NOT EXISTS `eb_sesame_score` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `min_score` INT NOT NULL COMMENT '最低',
  `max_score` INT NOT NULL COMMENT '最高',
  `money` INT NOT NULL COMMENT '匹配金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '芝麻分匹配';


-- -----------------------------------------------------
-- Table `eb_extra_credit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_extra_credit` ;

CREATE TABLE IF NOT EXISTS `eb_extra_credit` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `money` INT NOT NULL COMMENT '增加金额',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '拓展信用信息';


-- -----------------------------------------------------
-- Table `eb_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eb_order` ;

CREATE TABLE IF NOT EXISTS `eb_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `staff_no` VARCHAR(45) NOT NULL COMMENT '员工号',
  `staff_id` BIGINT(20) NOT NULL COMMENT '员工ID',
  `apply_id` BIGINT(20) NULL DEFAULT 0 COMMENT '申请信息ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
  `user_name` VARCHAR(64) NOT NULL COMMENT '用户姓名',
  `user_phone` VARCHAR(45) NOT NULL COMMENT '用户手机号',
  `id_card` VARCHAR(45) NOT NULL COMMENT '身份证号',
  `sesame_score` INT NOT NULL COMMENT '芝麻分',
  `exist_sb` SMALLINT(6) NULL DEFAULT 0 COMMENT '是否有社保 0 否 1 是',
  `exist_gjj` SMALLINT(6) NULL DEFAULT 0 COMMENT '是否有公积金: 0 否 1 是',
  `exist_car` SMALLINT(6) NULL DEFAULT 0 COMMENT '是否有车 0 否 1 是',
  `exist_house` SMALLINT(6) NULL DEFAULT 0 COMMENT '是否有房 0 否 1 是',
  `money` DECIMAL(20,2) NOT NULL COMMENT '交易金额',
  `state` SMALLINT(6) NULL DEFAULT 0 COMMENT '状态 0 待支付 1 支付成功  2 支付失败(取消)',
  `del` SMALLINT(6) NULL DEFAULT 0 COMMENT '是否删除 0 否 1 是',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `cancel_time` BIGINT(20) NULL DEFAULT 0 COMMENT '取消时间',
  `finish_time` TIMESTAMP NULL DEFAULT NULL COMMENT '完成时间(支付完成/支付失败)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '订单';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
